// Generated by the WOLips Templateengine Plug-in at 21.01.2016 11:39:32
package net.rujel.analytics;

import com.webobjects.foundation.NSLog;

import net.rujel.reusables.UTF8Application;

import com.webobjects.appserver.WOApplication;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WORequestHandler;
import com.webobjects.appserver.WOResponse;

public class Application extends UTF8Application {
	public static void main(String[] argv) {
		WOApplication.main(argv, Application.class);
	}

	public Application() {
		NSLog.out.appendln("Welcome to " + name() + " !");
		WORequestHandler directActionRequestHandler = requestHandlerForKey("wa");
		setDefaultRequestHandler(directActionRequestHandler);
		/* ** put your initialization code in here ** */
		setAllowsConcurrentRequestHandling(true);
	}
	
	public WOResponse handleException(Exception anException,  WOContext aContext) {
		return super.handleException(anException, aContext);
	}

}
