// Generated by the WOLips Templateengine Plug-in at 21.01.2016 11:39:32
package net.rujel.analytics;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOApplication;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOSession;
import com.webobjects.appserver.WODirectAction;

import net.rujel.analytics.components.Main;
import net.rujel.auth.LoginProcessor;
import net.rujel.reusables.SettingsReader;

public class DirectAction extends WODirectAction {
	public DirectAction(WORequest request) {
		super(request);
	}
	
	public WOActionResults loginAction() {
		context().request().setUserInfoForKey(Boolean.TRUE, "isLogin");
		return LoginProcessor.loginAction(context());
	}
	
	public WOActionResults refuseAction() {
		WOComponent result = pageWithName("LoginDialog");
		result.takeValueForKey("accessDenied", "message");
		return result;
	}

	public WOActionResults successAction() {
		return defaultAction();
	}

    public WOActionResults defaultAction() {
    	WOActionResults result;
		WOSession ses = WOApplication.application().restoreSessionWithID(
				request().sessionID(),context());
		if (ses != null && ses.valueForKey("user") != null) {
//			WOApplication.application().takeValueForKey(request(), "request");
			result = pageWithName(Main.class.getName());
		} else {
			if(SettingsReader.boolForKeyPath("auth.useHTTPS", true))
				result = LoginProcessor.secureRedirect("login",context(),Boolean.TRUE);
			else
				result = loginAction();
		}
		return result;
    }

}
