// Generated by the WOLips Templateengine Plug-in at 21.01.2016 11:39:32
package net.rujel.analytics;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOApplication;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.appserver.WOSession;
import com.webobjects.foundation.NSData;
import com.webobjects.appserver.WODirectAction;

import net.rujel.analytics.components.Main;
import net.rujel.auth.LoginProcessor;
import net.rujel.reusables.SettingsReader;

public class DirectAction extends WODirectAction {
	public DirectAction(WORequest request) {
		super(request);
	}
	
	public WOActionResults loginAction() {
		context().request().setUserInfoForKey(Boolean.TRUE, "isLogin");
		return LoginProcessor.loginAction(context());
	}
	
	public WOActionResults refuseAction() {
		WOComponent result = pageWithName("LoginDialog");
		result.takeValueForKey("accessDenied", "message");
		return result;
	}

	public WOActionResults successAction() {
		return defaultAction();
	}

    public WOActionResults defaultAction() {
    	WOActionResults result;
		WOSession ses = WOApplication.application().restoreSessionWithID(
				request().sessionID(),context());
		if (ses != null && ses.valueForKey("user") != null) {
//			WOApplication.application().takeValueForKey(request(), "request");
			result = pageWithName(Main.class.getName());
		} else {
			if(SettingsReader.boolForKeyPath("auth.useHTTPS", true))
				result = LoginProcessor.secureRedirect("login",context(),Boolean.TRUE);
			else
				result = loginAction();
		}
		return result;
    }

    public WOActionResults respondAction() {
    	Application app = (Application)WOApplication.application();
		WOResponse response = app.createResponseInContext(context());
		response.setHeader("text/plain; charset=UTF-8","Content-Type");
    	NSData content = context().request().content();
    	String schoolID = context().request().stringFormValueForKey("schoolID");
    	String queryID = context().request().stringFormValueForKey("queryID");
		if(schoolID == null || queryID == null) {
			response.appendContentString(
					"Here we only accept service responses with schoolID and queryID");
			response.setStatus(WOResponse.HTTP_STATUS_INTERNAL_ERROR);
			return response;
		}
		try {
			app.addResponse(content, schoolID, queryID);
			response.appendContentString("OK");

		} catch (Exception e) {
			// TODO: handle exception
			response.appendContentString("ERROR: ");
			response.appendContentString(e.toString());
			response.setStatus(WOResponse.HTTP_STATUS_INTERNAL_ERROR);
			e.printStackTrace();
		}
		return response;
    }
    
}
