// Generated by the WOLips Templateengine Plug-in at 21.01.2016 11:39:32
package net.rujel.analytics;

import com.webobjects.appserver.WOSession;

import net.rujel.auth.UserPresentation;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;
	public UserPresentation user;

	public Session() {
	}
	
}
